[package]
name = "smart-road"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.sdl2]
  version="*"
  features = ["use_mac_framework"]


[dependencies]
rand="0.8.5"